############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

#[[main]]
#name = "Shop"
#url = "https://drumline.quibtechmedia.com"
#weight = 3

[[main]]
name = "Music"
url = "/music"
weight = 5

[[main]]
parent = "Music"
name = "2025 Cadence"
url = "/2025-cadence"

[[main]]
parent = "Music"
name = "Jig 2"
url = "/jig-2"

[[main]]
parent = "Music"
name = "Ninja Disco"
url = "/ninja-disco"

[[main]]
parent = "Music"
name = "Walmart"
url = "/walmart"

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "/about"
weight = 2

[[footer]]
name = "Music"
url = "/music"
weight = 3

#[[footer]]
#name = "Shop"
#url = "https://drumline.quibtechmedia.com"
#weight = 2